/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Request {
  
}
export interface RequestInit {
  
}
export interface Response {
  
}
export function fetchWithStr(resource: string): Promise<Response>
export function fetchWithRequest(resource: Request): Promise<Response>
export function fetchWithStrAndInit(resource: string, init: RequestInit): Promise<Response>
export function fetchWithRequestAndInit(resource: Request, init: RequestInit): Promise<Response>
