/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Request {
  
}
export interface RequestInit {
  
}
export function fetchWithStr(resource: string): void
export function fetchWithRequest(resource: Request): void
export function fetchWithStrAndInit(resource: string, init: RequestInit): void
export function fetchWithRequestAndInit(resource: Request, init: RequestInit): void
